default_language_version:
    python: python3
repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: trailing-whitespace
  - id: flake8
    args: [--max-line-length=140]
  - id: check-yaml
  - id: check-added-large-files
  - id: debug-statements
  - id: end-of-file-fixer
  - id: check-ast
  - id: check-merge-conflict
  - id: detect-private-key
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.0.1
  hooks:
    - id: reorder-python-imports
      types: [file, python]
- repo: https://github.com/psf/black
  rev: stable
  hooks:
    - id: black
      language: python
      types: [file, python]
