cache: pip

language: python

python:
  - "3.7"
  - "3.6"

services:
  - postgresql

addons:
  postgresql: "9.6"

before_install:
  - pip install poetry
install:
  - poetry install

before_script:
  - psql -c "create database docbrown;" -U postgres
  - psql -c "create role docbrown with login password 'docbrown' createdb;" -U postgres
  - ./testproject/manage.py makemigrations

script: py.test --cov=model_history testproject

after_success:
  - poetry run codecov
